### ISSUE TITLE
[Error] Out of memory issue

### ISSUE THREAD

**Issue by Fir-lat** [qitianwu/GraphOOD-GNNSafe#4]
It turns out "Out of memory" if args.runs is larger than 2 (Run on A5000 24GB). 

It's not necessary to keep all the intermediate testing results in GPU memory in "logger.py".

**Comment by qitianwu** [comment]
Can you specify which dataset you use and how you run our codes? If you correctly follow the instruction in Readme, the OOM issue should not happen

**Comment by Fir-lat** [comment]
I followed the README.md and run as follows:
```
python main.py --method msp --backbone gcn --dataset amazon-photo --ood_type structure --mode detect --device 0 --use_bn --runs 5
```
